package com.co.autenticacionbiometricaapirest.pilotoautenticacionbiometrica.autenticacion.service;

import com.co.autenticacionbiometricaapirest.pilotoautenticacionbiometrica.autenticacion.model.UsuarioInfoBiometrica;

public interface UsuarioInfoBiometricaService {

	UsuarioInfoBiometrica almacenarEntidad(UsuarioInfoBiometrica usuarioInfoBiometrica);
}
