spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/autenticacion-biometrica?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: "jdbc:mysql://autenticacion-biometrica-test.cuhwiikx8iqy.us-east-1.rds.amazonaws.com:3306/autenticacion-biometrica"
    username: admin
    password: yoqYSY971
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect

---

spring:
  config:
    activate:
      on-profile: pilot
  datasource:
    url: "jdbc:mysql://localhost:3306/autenticacion-biometrica?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
---

amazon-properties:
  config:
    ak: ENC(dCX3n1WnXS/cKGZMIiOc/RyXKr3PTLtqxGLTEtWws7Y=)
    sk: ENC(wEyU5IqxlADHRH89KQw+wYNQTaLX37YNfo6NvLtf5NSUKXd8g74o/Jd/cJCsxbizIFwSoJ1CTEk=)
  registro:
    bucket-name: registro-biometrico
    bucket-file-context: registro-biometrico/
  autenticacion:
    bucket-name: autenticacion-biometrica
    bucket-file-context: tmp/
  aws-api-service:
    context: https://sna925yu4a.execute-api.us-east-1.amazonaws.com/
    registro:
      end-point: registro-biometrico
    autenticacion:
      end-point: autenticacion-biometrica

mensajes-sistema:
  archivo:
    error-creacion-archivo-en-servidor: Se produjo un error intentando crear el archivo temporal en el servidor.